sudo: required
dist: trusty
language: node_js
node_js:
    - '5.1'

before_script:
    - npm install -g grunt-cli
    - npm install grunt

script:
    - git config --global user.name "$GIT_NAME"
    - git config --global user.email "$GIT_EMAIL"
    - git config --global push.default simple
    - git clone --depth=1 https://$GH_TOKEN@github.com/UniqueStudio/uniquestudio.github.io.git _dist
    - npm run build

after_success:
    - cd _dist
    - rsync -a --delete --delete-after --exclude '.git' ../dist/ ./
    - cp ../CNAME .
    - git add -A .
    - git commit -a -m "update from travis, build $TRAVIS_BUILD_NUMBER at $(hostname)"
    - git push --quiet origin master

env:
  global:
    secure: "HI/ZK3GFOYt3go1Qer+Fu1mHwOuEKdw3snDQdC1Zh5f09ADmRYpM6SemIgciYah/9RSD2bTWdJp7KtMmERxUuPEh/org8TQAR51VkEUR6gCne6o7xklC8AtP8zM3x7CWL3IOtainE7tsfHMELdsvFmCVMy+v/MtfrmMFlXKPOmK7TeWM2EWruVq6rWp7HGfRi66J0rb4FxRTTqPV8YgopHhv9/MJNbFF35cBAktEESxtB7AAVj9xIgtidNk/zr4rJAIXeFTZoZTcbxvkQR4reK7EGUp41DoEFTwznbUuacDexz60v5v5i/qbfeuNygjX17dje7rMtN6dNQHXuxfLCqtBEp8t8eoH6ZNGca7SxvhFqzvlM/e+p7H2tkFbGXv1ftjolg9HkeAy9sQUbKhkFtMYX73GyT4ZOsY8EQfnf+8NVbauS+qJIFq1znvqN+/p5PqPyCOIFtQfGjSJ28XtWFAPKzqwxLs92IWuNMRZFqjk+PXtbrm/rYhf5pGb1ZoZOgMQ5jbdGUr1+Ly5BxzC0xZFY4F7OraJivu3ikB/7KdGudPMnTDehckvSLI0qRKcxLETpQBhPju9vhmZ5gARn7DqbsKtj8plmY8wvpI9ISa7WStV1A8mRPHGFrvSD8BABb6bCu+al4m7Uaq/1858q1VEzxBoACShr+Xu76M3da8="
